### ISSUE TITLE
Zadanie #01

### ISSUE THREAD

**Issue by emsi-iggy** [emsi-iggy/Building-Info#2]
Stworzenie metody zwracającej parametry powierzchni lokalizacji klientowi.

**Comment by tomdziwood** [comment]
Heja, to w klasie "Pomieszczenie" metoda "getArea" załatwia sprawę, dobrze rozumiem?

**Comment by tomdziwood** [comment]
Ok, metody są zrobione dla pomieszczenia, poziomu, budynku. To by oznaczało koniec issue?
